# fly.toml app configuration file generated for dark-hill-9062 on 2023-09-16T22:36:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-hill-9062"
primary_region = "otp"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
